server:
  port: 9190
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    druid:
      url: jdbc:postgresql://10.27.26.94:6432/ooad
      username: postgres
      password: 123456
mybatis-plus:
  configuration:
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
