server:
  port: 9190
  servlet:
    session:
      timeout: 1800 # 设置会话超时时间为30分钟（30 * 60）
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    druid:
      url: jdbc:postgresql://10.27.26.94:6432/ooad
      username: postgres
      password: 123456
minio:
  endpoint: http://10.27.26.94:9000
  accessKey: admin
  secretKey: password
  bucketName: projecthelper
  userPath: user-img
#  buildingPath: builder-img
#  commentPath: comment-img
#  restaurantPath: restaurant-img
#  foodPath: food-img
#  busPath: bus-json
#  commodityPath: commodity-img
mybatis-plus:
  configuration:
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
