server:
  port: 9190
  servlet:
    session:
      timeout: 1800 # 设置会话超时时间为30分钟（30 * 60）
spring:
  mail:
    host: smtp.qq.com #邮件服务器地址
    port: 587 #端口号
    username: 2806187612@qq.com
    password: qellpwkeefuxdfjd
    default-encoding: UTF-8 #默认编码格式
    properties:
      mail:
        debug: false #启动debug调试
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory #SSL连接配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    druid:
      url: jdbc:postgresql://10.27.26.94:6432/ooad
      username: postgres
      password: 123456
minio:
  endpoint: http://10.27.26.94:9000
  accessKey: admin
  secretKey: password
  bucketName: projecthelper
  userPath: user-img
  filePath: file
#  buildingPath: builder-img
#  commentPath: comment-img
#  restaurantPath: restaurant-img
#  foodPath: food-img
#  busPath: bus-json
#  commodityPath: commodity-img
mybatis-plus:
  configuration:
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
