server:
  port: 9190
  servlet:
    session:
      timeout: 1800 # 设置会话超时时间为30分钟（30 * 60）
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    druid:
      url: jdbc:postgresql://10.27.26.94:6432/ooad
      username: postgres
      password: 123456
minio:
  endpoint: http://10.27.26.94:9090
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: projecthelper
  userPath: user-img
<<<<<<< HEAD
#  buildingPath: builder-img
#  commentPath: comment-img
#  restaurantPath: restaurant-img
#  foodPath: food-img
#  busPath: bus-json
#  commodityPath: commodity-img
=======
  buildingPath: builder-img
  commentPath: comment-img
  restaurantPath: restaurant-img
  foodPath: food-img
  busPath: bus-json
  commodityPath: commodity-img
>>>>>>> 5ea0e2336c7842714a46f7c3a45fd2429547003d
mybatis-plus:
  configuration:
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
